name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: Example implementation of CodelanxLib
author: 1Rogue
depend: [CodelanxLib]